views:
  - output: "index.html"
    query: "types.rq"
    template: "index.html"
  - output: "{{typeid}}.html"
    query: "types.rq"
    template: "type.html"
  - output: "{{placeid}}.html"
    query: "counties.rq"
    template: "county.html"
  - output: "{{placeid}}.html"
    query: "places.rq"
    template: "place.html"
