PREFIX afn: <http://jena.apache.org/ARQ/function#>
PREFIX nct: <http://n2t.net/ark:/39333/ncg/type#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT
?placeuri
?placeid
?placename
?description

WHERE {
  ?placeuri
    a nct:County ;
    skos:prefLabel ?placename ;
    skos:note ?note .

  BIND(afn:localname(?placeuri) AS ?placeid)
  BIND (CONCAT(IF(REGEX(?note, "^[A-Z]"), "", "… "), ?note) AS ?description)
}
