PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX nct:     <http://n2t.net/ark:/39333/ncg/type#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>

SELECT
?placeuri
?placeid
?placename
?description

WHERE {
  ?placeuri
    dcterms:type nct:county ;
    skos:prefLabel ?placename ;
    skos:note ?note .

  BIND (REPLACE(STR(?placeuri), "^(.*)/([^/]*)$", "$2") AS ?placeid)
  BIND (CONCAT(IF(REGEX(?note, "^[A-Z]"), "", "… "), ?note) AS ?description)
}
