PREFIX afn:     <http://jena.apache.org/ARQ/function#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ncv:     <http://n2t.net/ark:/39333/ncg/vocab#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX skosxl:  <http://www.w3.org/2008/05/skos-xl#>

SELECT
?placeid
?placename
?type

WHERE {
  ?placeuri
    dcterms:type ?typeuri ;
    skos:prefLabel ?placename ;
    ncv:county <{{.}}> .

  ?typeuri a skos:Concept ;
    (skosxl:prefLabel/ncv:plural/skosxl:literalForm) ?type .

  BIND (afn:localname(?placeuri) AS ?placeid)
}

ORDER BY LCASE(?type) ?placename
